#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
script_generator.py
根据配置文件生成 ModelSim 批处理脚本 (Tcl) 及可选的执行包装脚本。
支持直接运行测试（--run）和清理生成文件（--clean）。
Usage:
    python script_generator.py --config config.json
    python script_generator.py --config config.json --exec
    python script_generator.py --config config.json --exec --output-tcl my_script.do --output-exec run.sh
    python script_generator.py --run --config config.json
    python script_generator.py --clean --config config.json
    python script_generator.py --clean
"""

import argparse
import json
import os
import shutil
import sys
import tempfile
import subprocess
from pathlib import Path
import tkinter as tk
from tkinter import ttk, scrolledtext, messagebox


def collect_files(paths, extensions=None):
    """
    收集文件和目录中的所有文件。
    
    Args:
        paths: 路径列表（可以是文件或目录）
        extensions: 可选的文件扩展名列表，如 ['.v', '.sv']，如果为 None 则接受所有文件
    
    Returns:
        收集到的所有文件的路径列表（使用正斜杠 /）
    """
    if extensions is None:
        extensions = ['.v', '.sv', '.V', '.SV']
    
    collected = []
    for path in paths:
        path = Path(path)
        if path.is_file():
            # 使用 as_posix() 确保路径使用正斜杠 /
            collected.append(path.as_posix())
        elif path.is_dir():
            # 遍历目录，收集所有匹配的文件
            for ext in extensions:
                for p in path.rglob(f'*{ext}'):
                    # 使用 as_posix() 确保路径使用正斜杠 /
                    collected.append(p.as_posix())
        else:
            print(f"Warning: Path does not exist: {path}")
    
    return sorted(collected)


def generate_tcl_content(config):
    """
    根据配置生成 Tcl 脚本内容（字符串），不写入文件。
    config: 字典，与 generate_tcl_script 相同。
    """
    # 定义 Tcl 脚本模板，使用自定义占位符 {{...}}
    template = """# ModelSim Batch Script for 5-Stage Pipeline CPU Testing
# Generated by script_generator.py

# 配置变量（从配置文件读取）
set project_dir "{{PROJECT_DIR}}"
set ip_files [list {{IP_FILES_TCL}}]
set verilog_files [list {{VERILOG_FILES_TCL}}]
set testbench_file "{{TESTBENCH_FILE}}"
set testdata_dir "{{TESTDATA_DIR}}"
set results_dir "{{RESULTS_DIR}}"
set imem_file_path "{{IMEM_FILE_PATH}}"
set imem_readmemh_line {{IMEM_READMEMH_LINE}}
set top_module "{{TOP_MODULE}}"

# ============================================
# Clean up any existing libraries and files
# ============================================
if {[file exists work]} {
    vdel -lib work -all
}
catch {file delete _246tb_ex10_result.txt}

# Create fresh working library
vlib work

# ============================================
# 1. 编译 IP 核文件
# ============================================
foreach ip_file $ip_files {
    vlog -work work -quiet $ip_file
}

# ============================================
# 2. 编译所有 Verilog 源文件
# ============================================
foreach src_file $verilog_files {
    vlog -work work -quiet $src_file
}

# Compile testbench
vlog -work work -quiet $testbench_file

# ============================================
# 3. 创建结果目录
# ============================================
if {![file exists $results_dir]} {
    file mkdir $results_dir
}

# ============================================
# 4. 自动发现所有测试文件
# ============================================
proc get_test_files {} {
    global testdata_dir
    set hex_files [glob -nocomplain -directory $testdata_dir "*.hex.txt"]
    set result {}

    foreach file $hex_files {
        # 移除 ./ 前缀后直接保留完整相对路径
        set rel_file [string map [list "./" ""] $file]
        lappend result $rel_file
    }

    set sorted_result [lsort $result]
    return $sorted_result
}

set test_files [get_test_files]

puts "Found [llength $test_files] test files to run:"
foreach test_file $test_files {
    puts "  - $test_file"
}
puts ""

# ============================================
# 5. 单个测试运行过程
# ============================================
proc run_single_test {test_file results_dir} {
    global imem_file_path imem_readmemh_line top_module ip_files

    set test_name [file rootname [file tail $test_file]]
    set test_name [string map {.hex ""} $test_name]

    puts "\\n-----------------------------"
    puts "RUNNING TEST: $test_file"
    puts "-----------------------------"

    # Clean up old result files
    if {[file exists ./_246tb_ex10_result.txt]} {
        catch {file delete ./_246tb_ex10_result.txt}
    }

    # ========================================
    # 修改 IMEM 文件中的 $readmemh 路径
    # ========================================
    # 备份原始 IMEM 文件
    set imem_backup "${imem_file_path}.bak"
    if {[file exists $imem_file_path]} {
        file copy -force $imem_file_path $imem_backup
    }

    # 获取测试文件的绝对路径
    set test_file_abs [file normalize $test_file]

    # 读取 IMEM 文件内容
    set imem_fid [open $imem_file_path r]
    set imem_lines [split [read $imem_fid] "\\n"]
    close $imem_fid

    # 修改指定行的 $readmemh 语句
    set new_lines {}
    set line_num 0
    foreach line $imem_lines {
        incr line_num
        if {$line_num == $imem_readmemh_line} {
            # 替换为新的测试文件路径（使用绝对路径）
            append new_lines "        \\$readmemh(\\\"$test_file_abs\\\", IMEMreg);"
        } else {
            append new_lines "$line\\n"
        }
    }

    # 写回 IMEM 文件
    set imem_fid [open $imem_file_path w]
    puts -nonewline $imem_fid $new_lines
    close $imem_fid

    # 重新编译 IMEM 模块
    foreach ip_file $ip_files {
        vlog -work work -quiet $ip_file
    }
    vlog -work work -quiet $imem_file_path

    # ========================================
    # 6. 加载并运行仿真
    # ========================================
    vsim -quiet work.$top_module

    # Run simulation for maximum 100000ns
    run 100000ns

    # ========================================
    # 7. 保存仿真结果
    # ========================================
    set sim_result_file "./_246tb_ex10_result.txt"
    set output_result_file "$results_dir/${test_name}_sim_result.txt"

    if {[file exists $sim_result_file]} {
        file copy -force $sim_result_file $output_result_file
        puts "Saved simulation result to: $output_result_file"
    } else {
        puts "Warning: Simulation result file not found: $sim_result_file"
    }

    # ========================================
    # 8. 恢复原始 IMEM 文件
    # ========================================
    if {[file exists $imem_backup]} {
        file copy -force $imem_backup $imem_file_path
        file delete $imem_backup
    }

    # ========================================
    # 9. 复制标准结果文件
    # ========================================
    regsub {\\.hex\\.txt$} $test_file ".result.txt" std_result_file
    echo "$std_result_file"
    set output_std_result_file "$results_dir/${test_name}_std_result.txt"
    if {[file exists $std_result_file]} {
        file copy -force $std_result_file $output_std_result_file
        puts "Standard test result copied to: $output_std_result_file"
    } else {
        puts "Standard result file not found: $std_result_file"
        return 0
    }

    # ========================================
    # 10. 比较仿真结果与标准结果
    # ========================================
    set compare_result [catch {exec txt_compare --file1 $output_result_file --file2 $std_result_file --display detailed > "$results_dir/${test_name}_comparison_result.txt"} compare_output]

    set comp_file "$results_dir/${test_name}_comparison_result.txt"
    if {[file exists $comp_file]} {
        # 使用 GBK 编码读取文件（兼容 txt_compare 的中文输出）
        set comp_fid [open $comp_file r]
        fconfigure $comp_fid -encoding cp936
        set comp_content [read $comp_fid]
        close $comp_fid

        # Check if test passed
        set lines [split $comp_content "\\n"]
        set success 0
        foreach line $lines {
            if {[string match "*在指定检查条件下完全一致.*" $line]} {
                set success 1
                break
            }
        }

        if {$success} {
            puts "RESULT: PASS - $test_file"
            return 1
        } else {
            puts "RESULT: FAIL - $test_file"
            puts "Comparison output:"
            puts "=================================================================================="
            puts $comp_content
            puts "=================================================================================="
            return 0
        }
    } else {
        puts "Comparison result file not found: $comp_file"
        return 0
    }
}

# ============================================
# 11. 运行所有测试
# ============================================
set total_tests [llength $test_files]
set pass_count 0

puts "Starting batch simulation for $total_tests tests..."

foreach test_file $test_files {
    set result [run_single_test $test_file $results_dir]
    if {$result == 1} {
        incr pass_count
    }
}

# ============================================
# 12. 生成最终摘要
# ============================================
set summary_text [subst "BATCH TEST SUMMARY\\n==================================\\nTotal tests: $total_tests\\nPassed tests: $pass_count\\nFailed tests: [expr $total_tests - $pass_count]\\nSuccess rate: [format %.2f [expr double($pass_count)*100/double($total_tests)]]%\\n=================================="]

puts "\\n$summary_text"

# Write summary to file
set sum_fid [open "$results_dir/test_summary.txt" w]
puts $sum_fid $summary_text
close $sum_fid

puts "\\nAll tests completed. Results saved in $results_dir/"
puts "Success rate: [format %.2f [expr double($pass_count)*100/double($total_tests)]]%"

# Quit ModelSim
quit
"""

    # 准备替换内容
    ip_files_tcl = ' '.join([f'"{f}"' for f in config['ip_files']])
    verilog_files_tcl = ' '.join([f'"{f}"' for f in config['verilog_files']])

    # 替换占位符
    tcl_script = template.replace("{{PROJECT_DIR}}", config.get('project_dir', '.')) \
                         .replace("{{IP_FILES_TCL}}", ip_files_tcl) \
                         .replace("{{VERILOG_FILES_TCL}}", verilog_files_tcl) \
                         .replace("{{TESTBENCH_FILE}}", config['testbench_file']) \
                         .replace("{{TESTDATA_DIR}}", config['testdata_dir']) \
                         .replace("{{RESULTS_DIR}}", config['results_dir']) \
                         .replace("{{IMEM_FILE_PATH}}", config['imem_file_path']) \
                         .replace("{{IMEM_READMEMH_LINE}}", str(config['imem_readmemh_line'])) \
                         .replace("{{TOP_MODULE}}", config.get('top_module', 'test'))
    return tcl_script

def generate_tcl_script(config, output_tcl):
    """
    根据配置生成 Tcl 脚本内容并写入文件。
    """
    tcl_content = generate_tcl_content(config)
    with open(output_tcl, 'w', encoding='utf-8') as f:
        f.write(tcl_content)
    print(f"Generated Tcl script: {output_tcl}")

def generate_exec_wrapper(tcl_script, output_exec, log_file="log"):
    """
    生成执行包装脚本，调用 vsim 运行 Tcl 脚本并重定向输出。
    """
    if sys.platform.startswith('win'):
        content = f"""@echo off
vsim -c -do "do {tcl_script}; quit" > {log_file}
"""
    else:
        content = f"""#!/bin/sh
vsim -c -do "do {tcl_script}; quit" > {log_file}
"""
    with open(output_exec, 'w', encoding='utf-8') as f:
        f.write(content)
    if not sys.platform.startswith('win'):
        os.chmod(output_exec, 0o755)
    print(f"Generated execution wrapper: {output_exec}")

def run_vsim(tmp_file):
    """
    直接运行仿真：生成临时 Tcl 文件，调用 vsim，然后删除临时文件。
    输出重定向到 log 目录下带日期标签的文件。
    """
    from datetime import datetime
    
    # 创建 log 目录（如果不存在）
    log_dir = Path("log")
    log_dir.mkdir(parents=True, exist_ok=True)
    
    # 生成带日期时间戳的日志文件名
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = log_dir / f"sim_{timestamp}.log"
    
    # 构建 vsim 命令
    if sys.platform.startswith('win'):
        cmd = ['vsim', '-c', '-do', f'do {tmp_file}; quit']
    else:
        cmd = ['vsim', '-c', '-do', f'do {tmp_file}; quit']
    
    print(f"Running: {' '.join(cmd)}")
    print(f"Logging to: {log_file}")
    
    # 执行命令，将输出写入日志文件
    with open(log_file, 'w', encoding='utf-8') as log_fid:
        process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)
        for line in process.stdout:
            log_fid.write(line)
            log_fid.flush()  # 确保实时写入
        process.wait()
        if process.returncode != 0:
            log_fid.write(f"Warning: vsim exited with code {process.returncode}\n")
            print(f"Warning: vsim exited with code {process.returncode}")
    
    print(f"Simulation completed. Log saved to: {log_file}")
    

def show_gui_results(results_dir, testdata_dir):
    """
    使用 GUI 展示测试结果，按测试用例分组，展示 hex/txt/sim_result/std_result。
    """
    # 收集所有测试用例
    testdata_path = Path(testdata_dir)
    results_path = Path(results_dir)
    
    # 获取所有 hex.txt 文件
    hex_files = sorted(testdata_path.glob('*.hex.txt'))
    
    if not hex_files:
        messagebox.showerror("错误", f"在 {testdata_dir} 中未找到测试文件")
        return
    
    # 创建主窗口
    root = tk.Tk()
    root.title("CPU 测试结果查看器")
    root.geometry("1200x800")
    
    # 创建主框架
    main_frame = ttk.Frame(root, padding="10")
    main_frame.pack(fill=tk.BOTH, expand=True)
    
    # 左侧：测试用例列表
    left_frame = ttk.Frame(main_frame)
    left_frame.pack(side=tk.LEFT, fill=tk.Y, padx=(0, 10))
    
    ttk.Label(left_frame, text="测试用例列表", font=('Arial', 10, 'bold')).pack(pady=(0, 5))
    
    # 创建列表框
    listbox_frame = ttk.Frame(left_frame)
    listbox_frame.pack(fill=tk.BOTH, expand=True)
    
    scrollbar = ttk.Scrollbar(listbox_frame)
    scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
    
    test_listbox = tk.Listbox(listbox_frame, width=40, yscrollcommand=scrollbar.set, font=('Consolas', 9))
    test_listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
    scrollbar.config(command=test_listbox.yview)
    
    # 填充测试用例列表
    test_cases = []
    for hex_file in hex_files:
        test_name = hex_file.stem.replace('.hex', '')
        test_cases.append({
            'name': test_name,
            'hex_file': hex_file,
            'txt_file': hex_file.with_suffix('').with_suffix('').with_suffix(".txt"),  # 去掉 .txt
            'sim_result': results_path / f'{test_name}_sim_result.txt',
            'std_result': results_path / f'{test_name}_std_result.txt',
            'comparison_result': results_path / f'{test_name}_comparison_result.txt'
        })
        test_listbox.insert(tk.END, test_name)

    # 右侧：文件内容显示区
    right_frame = ttk.Frame(main_frame)
    right_frame.pack(side=tk.RIGHT, fill=tk.BOTH, expand=True)

    # 创建 Notebook (标签页)
    notebook = ttk.Notebook(right_frame)
    notebook.pack(fill=tk.BOTH, expand=True)

    # 创建五个标签页
    tabs = {}
    for tab_name in ['hex', 'txt', 'sim_result', 'std_result', 'comparison_result']:
        tab_frame = ttk.Frame(notebook)
        notebook.add(tab_frame, text=tab_name)

        text_widget = scrolledtext.ScrolledText(tab_frame, wrap=tk.WORD, font=('Consolas', 9))
        text_widget.pack(fill=tk.BOTH, expand=True, padx=5, pady=5)
        text_widget.config(state=tk.DISABLED)

        tabs[tab_name] = text_widget
    
    def load_test_content(event=None):
        """加载选中测试用例的内容"""
        selection = test_listbox.curselection()
        if not selection:
            return
        
        test_case = test_cases[selection[0]]
        test_name = test_case['name']
        
        # 清空所有内容
        for tab_name, text_widget in tabs.items():
            text_widget.config(state=tk.NORMAL)
            text_widget.delete('1.0', tk.END)
        
        # 读取并显示 hex 文件
        try:
            hex_file = test_case['hex_file']
            if hex_file.exists():
                with open(hex_file, 'r', encoding='utf-8') as f:
                    content = f.read()
                tabs['hex'].config(state=tk.NORMAL)
                tabs['hex'].insert('1.0', content)
            else:
                tabs['hex'].config(state=tk.NORMAL)
                tabs['hex'].insert('1.0', f'文件不存在: {hex_file}')
        except Exception as e:
            tabs['hex'].config(state=tk.NORMAL)
            tabs['hex'].insert('1.0', f'读取失败: {e}')
        finally:
            tabs['hex'].config(state=tk.DISABLED)
        
        # 读取并显示 txt 文件 (汇编源码)
        try:
            txt_file = test_case['txt_file']
            if txt_file.exists():
                with open(txt_file, 'r', encoding='utf-8') as f:
                    content = f.read()
                tabs['txt'].config(state=tk.NORMAL)
                tabs['txt'].insert('1.0', content)
            else:
                tabs['txt'].config(state=tk.NORMAL)
                tabs['txt'].insert('1.0', f'文件不存在: {txt_file}')
        except Exception as e:
            tabs['txt'].config(state=tk.NORMAL)
            tabs['txt'].insert('1.0', f'读取失败: {e}')
        finally:
            tabs['txt'].config(state=tk.DISABLED)
        
        # 读取并显示仿真结果
        try:
            sim_result = test_case['sim_result']
            if sim_result.exists():
                with open(sim_result, 'r', encoding='cp936') as f:
                    content = f.read()
                tabs['sim_result'].config(state=tk.NORMAL)
                tabs['sim_result'].insert('1.0', content)
            else:
                tabs['sim_result'].config(state=tk.NORMAL)
                tabs['sim_result'].insert('1.0', f'文件不存在: {sim_result}')
        except Exception as e:
            tabs['sim_result'].config(state=tk.NORMAL)
            tabs['sim_result'].insert('1.0', f'读取失败: {e}')
        finally:
            tabs['sim_result'].config(state=tk.DISABLED)
        
        # 读取并显示标准结果
        try:
            std_result = test_case['std_result']
            if std_result.exists():
                with open(std_result, 'r', encoding='utf-8') as f:
                    content = f.read()
                tabs['std_result'].config(state=tk.NORMAL)
                tabs['std_result'].insert('1.0', content)
            else:
                tabs['std_result'].config(state=tk.NORMAL)
                tabs['std_result'].insert('1.0', f'文件不存在: {std_result}')
        except Exception as e:
            tabs['std_result'].config(state=tk.NORMAL)
            tabs['std_result'].insert('1.0', f'读取失败: {e}')
        finally:
            tabs['std_result'].config(state=tk.DISABLED)
        
        # 读取并显示比对结果
        try:
            comparison_result = test_case['comparison_result']
            if comparison_result.exists():
                with open(comparison_result, 'r', encoding='cp936') as f:
                    content = f.read()
                tabs['comparison_result'].config(state=tk.NORMAL)
                tabs['comparison_result'].insert('1.0', content)
            else:
                tabs['comparison_result'].config(state=tk.NORMAL)
                tabs['comparison_result'].insert('1.0', f'文件不存在: {comparison_result}')
        except Exception as e:
            tabs['comparison_result'].config(state=tk.NORMAL)
            tabs['comparison_result'].insert('1.0', f'读取失败: {e}')
        finally:
            tabs['comparison_result'].config(state=tk.DISABLED)
    
    # 绑定选择事件
    test_listbox.bind('<<ListboxSelect>>', load_test_content)
    
    # 默认选中第一个测试用例
    if test_cases:
        test_listbox.selection_set(0)
        load_test_content()
    
    # 添加统计信息和日志按钮
    stats_frame = ttk.Frame(main_frame)
    stats_frame.pack(fill=tk.X, pady=(10, 0))
    
    # 统计通过/失败数量
    pass_count = 0
    fail_count = 0
    for test_case in test_cases:
        sim_result = test_case['sim_result']
        std_result = test_case['std_result']
        if sim_result.exists() and std_result.exists():
            try:
                with open(sim_result, 'r', encoding='cp936') as f:
                    sim_content = f.read()
                with open(std_result, 'r', encoding='utf-8') as f:
                    std_content = f.read()
                if sim_content.strip() == std_content.strip():
                    pass_count += 1
                else:
                    fail_count += 1
            except:
                fail_count += 1
        else:
            fail_count += 1
    
    # 统计信息标签
    stats_label = ttk.Label(stats_frame, 
              text=f"总计: {len(test_cases)} 个测试 | 通过: {pass_count} | 失败: {fail_count} | 通过率: {pass_count/len(test_cases)*100:.1f}%" if test_cases else "无测试用例",
              font=('Arial', 10, 'bold'))
    stats_label.pack(side=tk.LEFT, padx=(0, 10))
    
    # 添加打开日志文件的按钮
    def open_latest_log():
        """打开最新的仿真日志文件"""
        log_dir = Path("log")
        if not log_dir.exists():
            messagebox.showwarning("警告", "日志目录不存在")
            return
        
        # 获取所有 .log 文件
        log_files = sorted(log_dir.glob("*.log"), key=os.path.getmtime, reverse=True)
        if not log_files:
            messagebox.showwarning("警告", "未找到日志文件")
            return
        
        # 打开最新的日志文件
        latest_log = log_files[0]
        try:
            if sys.platform.startswith('win'):
                os.startfile(latest_log)
            elif sys.platform == 'darwin':
                subprocess.Popen(['open', latest_log])
            else:
                subprocess.Popen(['xdg-open', latest_log])
        except Exception as e:
            messagebox.showerror("错误", f"无法打开日志文件: {e}")
    
    log_button = ttk.Button(stats_frame, text="📄 打开最新仿真日志", command=open_latest_log)
    log_button.pack(side=tk.LEFT)
    
    root.mainloop()


def clean_generated_files(config_file, tcl_script, exec_script):
    """
    清理生成的文件。
    """
    if os.path.exists(tcl_script):
        os.remove(tcl_script)
        print(f"Removed: {tcl_script}")

    if exec_script and os.path.exists(exec_script):
        os.remove(exec_script)
        print(f"Removed: {exec_script}")

    if config_file and os.path.exists(config_file):
        try:
            with open(config_file, 'r', encoding='utf-8') as f:
                config = json.load(f)
            results_dir = config.get('results_dir')
            if results_dir and os.path.exists(results_dir):
                shutil.rmtree(results_dir)
                print(f"Removed results directory: {results_dir}")
        except Exception as e:
            print(f"Warning: Could not read config file to clean results_dir: {e}")

    temp_file = "_246tb_ex10_result.txt"
    if os.path.exists(temp_file):
        os.remove(temp_file)
        print(f"Removed temporary file: {temp_file}")

def main():
    parser = argparse.ArgumentParser(description="Generate ModelSim batch script from config.")
    parser.add_argument("--config", default="config.json", help="Path to JSON configuration file.")
    parser.add_argument("--exec", action="store_true", help="Generate execution wrapper script to run vsim.")
    parser.add_argument("--output-tcl", default="run_cpu_tests.do", help="Output Tcl script filename (default: run_cpu_tests.do).")
    parser.add_argument("--output-exec", default=None, help="Output execution wrapper filename (default: run_vsim.sh/.bat).")
    parser.add_argument("--clean", action="store_true", help="Clean all generated files (scripts and results directory).")
    parser.add_argument("--not_run", action="store_true", help="NOT !!! Run simulation directly without generating scripts.")
    parser.add_argument("--gui", action="store_true", help="Show test results in GUI after simulation.")
    args = parser.parse_args()

    # 清理模式
    if args.clean:
        if args.output_exec is None:
            default_exec = "run_vsim.bat" if sys.platform.startswith('win') else "run_vsim.sh"
        else:
            default_exec = args.output_exec
        clean_generated_files(args.config, args.output_tcl, default_exec)
        return

    # 正常生成模式
    if not args.config:
        print("Error: --config is required for generation mode.")
        sys.exit(1)

    try:
        with open(args.config, 'r', encoding='utf-8') as f:
            config = json.load(f)
    except Exception as e:
        print(f"Error reading config file: {e}")
        sys.exit(1)

    required_keys = ['ip_files', 'verilog_files', 'testbench_file', 'testdata_dir', 'results_dir', 'imem_file_path', 'imem_readmemh_line']
    for key in required_keys:
        if key not in config:
            print(f"Missing required key in config: {key}")
            sys.exit(1)

    # 处理 verilog_files 和 ip_files：支持文件和目录混合配置
    # 如果配置项是目录，则自动遍历其中所有 Verilog 文件
    print("Collecting Verilog files...")
    config['verilog_files'] = collect_files(config['verilog_files'])
    print(f"  Found {len(config['verilog_files'])} Verilog source files")
    
    if config.get('ip_files'):
        config['ip_files'] = collect_files(config['ip_files'])
        print(f"  Found {len(config['ip_files'])} IP files")
    
    # 输出文件列表（调试信息）
    for f in config['verilog_files']:
        print(f"    - {f}")

    generate_tcl_script(config, args.output_tcl)


    if args.exec:
        if args.output_exec is None:
            default_exec = "run_vsim.bat" if sys.platform.startswith('win') else "run_vsim.sh"
        else:
            default_exec = args.output_exec
        generate_exec_wrapper(args.output_tcl, default_exec)
    elif not args.not_run:
        pass
        #run_vsim(args.output_tcl)
    
    # 如果指定了 --gui 选项，显示 GUI 结果查看器
    if args.gui:
        print("Launching GUI results viewer...")
        show_gui_results(config['results_dir'], config['testdata_dir'])
    
    print("Done.")

if __name__ == '__main__':
    main()