#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
script_generator.py
根据配置文件生成 ModelSim 批处理脚本 (Tcl) 及可选的执行包装脚本。
支持直接运行测试（--run）和清理生成文件（--clean）。
Usage:
    python script_generator.py --config config.json
    python script_generator.py --config config.json --exec
    python script_generator.py --config config.json --exec --output-tcl my_script.do --output-exec run.sh
    python script_generator.py --run --config config.json
    python script_generator.py --clean --config config.json
    python script_generator.py --clean
"""

import argparse
import json
import os
import shutil
import sys
import tempfile
import subprocess
from pathlib import Path


def collect_files(paths, extensions=None):
    """
    收集文件和目录中的所有文件。
    
    Args:
        paths: 路径列表（可以是文件或目录）
        extensions: 可选的文件扩展名列表，如 ['.v', '.sv']，如果为 None 则接受所有文件
    
    Returns:
        收集到的所有文件的路径列表（使用正斜杠 /）
    """
    if extensions is None:
        extensions = ['.v', '.sv', '.V', '.SV']
    
    collected = []
    for path in paths:
        path = Path(path)
        if path.is_file():
            # 使用 as_posix() 确保路径使用正斜杠 /
            collected.append(path.as_posix())
        elif path.is_dir():
            # 遍历目录，收集所有匹配的文件
            for ext in extensions:
                for p in path.rglob(f'*{ext}'):
                    # 使用 as_posix() 确保路径使用正斜杠 /
                    collected.append(p.as_posix())
        else:
            print(f"Warning: Path does not exist: {path}")
    
    return sorted(collected)


def generate_tcl_content(config):
    """
    根据配置生成 Tcl 脚本内容（字符串），不写入文件。
    config: 字典，与 generate_tcl_script 相同。
    """
    # 定义 Tcl 脚本模板，使用自定义占位符 {{...}}
    template = """# ModelSim Batch Script for 5-Stage Pipeline CPU Testing
# Generated by script_generator.py

# 配置变量（从配置文件读取）
set project_dir "{{PROJECT_DIR}}"
set ip_files [list {{IP_FILES_TCL}}]
set verilog_files [list {{VERILOG_FILES_TCL}}]
set testbench_file "{{TESTBENCH_FILE}}"
set testdata_dir "{{TESTDATA_DIR}}"
set results_dir "{{RESULTS_DIR}}"
set imem_file_path "{{IMEM_FILE_PATH}}"
set imem_readmemh_line {{IMEM_READMEMH_LINE}}
set top_module "{{TOP_MODULE}}"

# ============================================
# Clean up any existing libraries and files
# ============================================
if {[file exists work]} {
    vdel -lib work -all
}
catch {file delete _246tb_ex10_result.txt}

# Create fresh working library
vlib work

# ============================================
# 1. 编译 IP 核文件
# ============================================
foreach ip_file $ip_files {
    vlog -work work -quiet $ip_file
}

# ============================================
# 2. 编译所有 Verilog 源文件
# ============================================
foreach src_file $verilog_files {
    vlog -work work -quiet $src_file
}

# Compile testbench
vlog -work work -quiet $testbench_file

# ============================================
# 3. 创建结果目录
# ============================================
if {![file exists $results_dir]} {
    file mkdir $results_dir
}

# ============================================
# 4. 自动发现所有测试文件
# ============================================
proc get_test_files {} {
    global testdata_dir
    set hex_files [glob -nocomplain -directory $testdata_dir "*.hex.txt"]
    set result {}

    foreach file $hex_files {
        # 移除 ./ 前缀后直接保留完整相对路径
        set rel_file [string map [list "./" ""] $file]
        lappend result $rel_file
    }

    set sorted_result [lsort $result]
    return $sorted_result
}

set test_files [get_test_files]

puts "Found [llength $test_files] test files to run:"
foreach test_file $test_files {
    puts "  - $test_file"
}
puts ""

# ============================================
# 5. 单个测试运行过程
# ============================================
proc run_single_test {test_file results_dir} {
    global imem_file_path imem_readmemh_line top_module ip_files

    set test_name [file rootname [file tail $test_file]]
    set test_name [string map {.hex ""} $test_name]

    puts "\\n-----------------------------"
    puts "RUNNING TEST: $test_file"
    puts "-----------------------------"

    # Clean up old result files
    if {[file exists ./_246tb_ex10_result.txt]} {
        catch {file delete ./_246tb_ex10_result.txt}
    }

    # ========================================
    # 修改 IMEM 文件中的 $readmemh 路径
    # ========================================
    # 备份原始 IMEM 文件
    set imem_backup "${imem_file_path}.bak"
    if {[file exists $imem_file_path]} {
        file copy -force $imem_file_path $imem_backup
    }

    # 获取测试文件的绝对路径
    set test_file_abs [file normalize $test_file]

    # 读取 IMEM 文件内容
    set imem_fid [open $imem_file_path r]
    set imem_lines [split [read $imem_fid] "\\n"]
    close $imem_fid

    # 修改指定行的 $readmemh 语句
    set new_lines {}
    set line_num 0
    foreach line $imem_lines {
        incr line_num
        if {$line_num == $imem_readmemh_line} {
            # 替换为新的测试文件路径（使用绝对路径）
            append new_lines "        \\$readmemh(\\\"$test_file_abs\\\", IMEMreg);"
        } else {
            append new_lines "$line\\n"
        }
    }

    # 写回 IMEM 文件
    set imem_fid [open $imem_file_path w]
    puts -nonewline $imem_fid $new_lines
    close $imem_fid

    # 重新编译 IMEM 模块
    foreach ip_file $ip_files {
        vlog -work work -quiet $ip_file
    }
    vlog -work work -quiet $imem_file_path

    # ========================================
    # 6. 加载并运行仿真
    # ========================================
    vsim -quiet work.$top_module

    # Run simulation for maximum 100000ns
    run 100000ns

    # ========================================
    # 7. 保存仿真结果
    # ========================================
    set sim_result_file "./_246tb_ex10_result.txt"
    set output_result_file "$results_dir/${test_name}_sim_result.txt"

    if {[file exists $sim_result_file]} {
        file copy -force $sim_result_file $output_result_file
        puts "Saved simulation result to: $output_result_file"
    } else {
        puts "Warning: Simulation result file not found: $sim_result_file"
    }

    # ========================================
    # 8. 恢复原始 IMEM 文件
    # ========================================
    if {[file exists $imem_backup]} {
        file copy -force $imem_backup $imem_file_path
        file delete $imem_backup
    }

    # ========================================
    # 9. 复制标准结果文件
    # ========================================
    regsub {\\.hex\\.txt$} $test_file ".result.txt" std_result_file
    echo "$std_result_file"
    set output_std_result_file "$results_dir/${test_name}_std_result.txt"
    if {[file exists $std_result_file]} {
        file copy -force $std_result_file $output_std_result_file
        puts "Standard test result copied to: $output_std_result_file"
    } else {
        puts "Standard result file not found: $std_result_file"
        return 0
    }

    # ========================================
    # 10. 比较仿真结果与标准结果
    # ========================================
    set compare_result [catch {exec txt_compare --file1 $output_result_file --file2 $std_result_file --display detailed > "$results_dir/${test_name}_comparison_result.txt"} compare_output]

    set comp_file "$results_dir/${test_name}_comparison_result.txt"
    if {[file exists $comp_file]} {
        # 使用 GBK 编码读取文件（兼容 txt_compare 的中文输出）
        set comp_fid [open $comp_file r]
        fconfigure $comp_fid -encoding cp936
        set comp_content [read $comp_fid]
        close $comp_fid

        # Check if test passed
        set lines [split $comp_content "\\n"]
        set success 0
        foreach line $lines {
            if {[string match "*在指定检查条件下完全一致.*" $line]} {
                set success 1
                break
            }
        }

        if {$success} {
            puts "RESULT: PASS - $test_file"
            return 1
        } else {
            puts "RESULT: FAIL - $test_file"
            puts "Comparison output:"
            puts "=================================================================================="
            puts $comp_content
            puts "=================================================================================="
            return 0
        }
    } else {
        puts "Comparison result file not found: $comp_file"
        return 0
    }
}

# ============================================
# 11. 运行所有测试
# ============================================
set total_tests [llength $test_files]
set pass_count 0

puts "Starting batch simulation for $total_tests tests..."

foreach test_file $test_files {
    set result [run_single_test $test_file $results_dir]
    if {$result == 1} {
        incr pass_count
    }
}

# ============================================
# 12. 生成最终摘要
# ============================================
set summary_text [subst "BATCH TEST SUMMARY\\n==================================\\nTotal tests: $total_tests\\nPassed tests: $pass_count\\nFailed tests: [expr $total_tests - $pass_count]\\nSuccess rate: [format %.2f [expr double($pass_count)*100/double($total_tests)]]%\\n=================================="]

puts "\\n$summary_text"

# Write summary to file
set sum_fid [open "$results_dir/test_summary.txt" w]
puts $sum_fid $summary_text
close $sum_fid

puts "\\nAll tests completed. Results saved in $results_dir/"
puts "Success rate: [format %.2f [expr double($pass_count)*100/double($total_tests)]]%"

# Quit ModelSim
quit
"""

    # 准备替换内容
    ip_files_tcl = ' '.join([f'"{f}"' for f in config['ip_files']])
    verilog_files_tcl = ' '.join([f'"{f}"' for f in config['verilog_files']])

    # 替换占位符
    tcl_script = template.replace("{{PROJECT_DIR}}", config.get('project_dir', '.')) \
                         .replace("{{IP_FILES_TCL}}", ip_files_tcl) \
                         .replace("{{VERILOG_FILES_TCL}}", verilog_files_tcl) \
                         .replace("{{TESTBENCH_FILE}}", config['testbench_file']) \
                         .replace("{{TESTDATA_DIR}}", config['testdata_dir']) \
                         .replace("{{RESULTS_DIR}}", config['results_dir']) \
                         .replace("{{IMEM_FILE_PATH}}", config['imem_file_path']) \
                         .replace("{{IMEM_READMEMH_LINE}}", str(config['imem_readmemh_line'])) \
                         .replace("{{TOP_MODULE}}", config.get('top_module', 'test'))
    return tcl_script

def generate_tcl_script(config, output_tcl):
    """
    根据配置生成 Tcl 脚本内容并写入文件。
    """
    tcl_content = generate_tcl_content(config)
    with open(output_tcl, 'w', encoding='utf-8') as f:
        f.write(tcl_content)
    print(f"Generated Tcl script: {output_tcl}")

def generate_exec_wrapper(tcl_script, output_exec, log_file="log"):
    """
    生成执行包装脚本，调用 vsim 运行 Tcl 脚本并重定向输出。
    """
    if sys.platform.startswith('win'):
        content = f"""@echo off
vsim -c -do "do {tcl_script}; quit" > {log_file}
"""
    else:
        content = f"""#!/bin/sh
vsim -c -do "do {tcl_script}; quit" > {log_file}
"""
    with open(output_exec, 'w', encoding='utf-8') as f:
        f.write(content)
    if not sys.platform.startswith('win'):
        os.chmod(output_exec, 0o755)
    print(f"Generated execution wrapper: {output_exec}")

def run_vsim(tmp_file):
    """
    直接运行仿真：生成临时 Tcl 文件，调用 vsim，然后删除临时文件。
    输出重定向到 log 目录下带日期标签的文件。
    """
    from datetime import datetime
    
    # 创建 log 目录（如果不存在）
    log_dir = Path("log")
    log_dir.mkdir(parents=True, exist_ok=True)
    
    # 生成带日期时间戳的日志文件名
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = log_dir / f"sim_{timestamp}.log"
    
    # 构建 vsim 命令
    if sys.platform.startswith('win'):
        cmd = ['vsim', '-c', '-do', f'do {tmp_file}; quit']
    else:
        cmd = ['vsim', '-c', '-do', f'do {tmp_file}; quit']
    
    print(f"Running: {' '.join(cmd)}")
    print(f"Logging to: {log_file}")
    
    # 执行命令，将输出写入日志文件
    with open(log_file, 'w', encoding='utf-8') as log_fid:
        process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)
        for line in process.stdout:
            log_fid.write(line)
            log_fid.flush()  # 确保实时写入
        process.wait()
        if process.returncode != 0:
            log_fid.write(f"Warning: vsim exited with code {process.returncode}\n")
            print(f"Warning: vsim exited with code {process.returncode}")
    
    print(f"Simulation completed. Log saved to: {log_file}")


def show_gui_results(results_dir, testdata_dir):
    """
    使用 PyQt5 GUI 展示测试结果，按测试用例分组，展示 5 个文件。
    """
    from PyQt5.QtWidgets import (QApplication, QMainWindow, QWidget, QVBoxLayout,
                                 QHBoxLayout, QListWidget, QListWidgetItem, QTabWidget,
                                 QTextEdit, QLabel, QPushButton, QSplitter, QFrame,
                                 QMessageBox)
    from PyQt5.QtCore import Qt
    from PyQt5.QtGui import QFont, QColor

    app = QApplication(sys.argv)
    app.setStyle('Fusion')

    # 创建主窗口
    window = QMainWindow()
    window.setWindowTitle("CPU 测试结果查看器")
    window.setGeometry(100, 100, 1400, 900)

    # 收集所有测试用例
    testdata_path = Path(testdata_dir)
    results_path = Path(results_dir)
    hex_files = sorted(testdata_path.glob('*.hex.txt'))

    if not hex_files:
        QMessageBox.warning(window, "警告", f"在 {testdata_dir} 中未找到测试文件")
        sys.exit(1)

    # 数据收集
    test_cases = []
    test_results = {}

    for hex_file in hex_files:
        test_name = hex_file.stem.replace('.hex', '')
        test_cases.append({
            'name': test_name,
            'hex_file': hex_file,
            'txt_file': hex_file.with_suffix('').with_suffix('').with_suffix(".txt"),
            'sim_result': results_path / f'{test_name}_sim_result.txt',
            'std_result': results_path / f'{test_name}_std_result.txt',
            'comparison_result': results_path / f'{test_name}_comparison_result.txt'
        })

        # 检查测试结果
        sim_result = test_cases[-1]['sim_result']
        std_result = test_cases[-1]['std_result']

        if sim_result.exists() and std_result.exists():
            try:
                with open(sim_result, 'r', encoding='cp936') as f:
                    sim_content = f.read()
                with open(std_result, 'r', encoding='utf-8') as f:
                    std_content = f.read()
                if sim_content.strip() == std_content.strip():
                    test_results[test_name] = 'pass'
                else:
                    test_results[test_name] = 'fail'
            except:
                test_results[test_name] = 'fail'
        else:
            test_results[test_name] = 'unknown'

    # 统计
    pass_count = sum(1 for r in test_results.values() if r == 'pass')
    fail_count = sum(1 for r in test_results.values() if r == 'fail')
    total = len(test_cases)

    # 中央部件
    central_widget = QWidget()
    window.setCentralWidget(central_widget)
    main_layout = QVBoxLayout(central_widget)
    main_layout.setContentsMargins(5, 5, 5, 5)
    main_layout.setSpacing(5)

    # 主分割器（垂直方向：上下 2:1）
    main_splitter = QSplitter(Qt.Vertical)

    # ===== 上半部分：测试用例列表 + 文件内容 =====
    top_splitter = QSplitter(Qt.Horizontal)

    # 左侧：测试用例列表
    left_widget = QWidget()
    left_layout = QVBoxLayout(left_widget)
    left_layout.setContentsMargins(0, 0, 0, 0)
    left_layout.setSpacing(2)

    title_label = QLabel("测试用例列表")
    title_label.setFont(QFont("Microsoft YaHei", 10, QFont.Bold))
    title_label.setStyleSheet("padding: 5px; background-color: #f0f0f0; border: 1px solid #ccc;")
    left_layout.addWidget(title_label)

    test_list = QListWidget()
    test_list.setFont(QFont("Consolas", 9))
    left_layout.addWidget(test_list)

    top_splitter.addWidget(left_widget)

    # 右侧：文件内容显示区（5 个标签页，不含日志）
    right_widget = QWidget()
    right_layout = QVBoxLayout(right_widget)
    right_layout.setContentsMargins(0, 0, 0, 0)
    right_layout.setSpacing(2)

    tab_widget = QTabWidget()
    tab_widget.setStyleSheet("""
        QTabWidget::pane { border: 1px solid #ccc; }
        QTabBar::tab { padding: 5px 15px; margin-right: 2px; }
        QTabBar::tab:selected { background-color: #fff; border-bottom-color: #fff; }
    """)

    tabs = {}
    tab_names = [
        ('hex', 'HEX 机器码'),
        ('txt', '汇编源码'),
        ('sim_result', '仿真输出'),
        ('std_result', '标准输出'),
        ('comparison_result', '比对结果')
    ]

    for tab_id, tab_title in tab_names:
        text_edit = QTextEdit()
        text_edit.setReadOnly(True)
        text_edit.setFont(QFont("Consolas", 9))
        text_edit.setStyleSheet("padding: 5px;")
        tab_widget.addTab(text_edit, tab_title)
        tabs[tab_id] = text_edit

    right_layout.addWidget(tab_widget)
    top_splitter.addWidget(right_widget)

    top_splitter.setStretchFactor(0, 3)
    top_splitter.setStretchFactor(1, 7)
    top_splitter.setSizes([400, 1000])

    main_splitter.addWidget(top_splitter)

    # ===== 下半部分：总览信息（左侧统计 + 右侧仿真日志） =====
    bottom_splitter = QSplitter(Qt.Horizontal)

    # 左侧：统计信息
    stats_widget = QFrame()
    stats_widget.setStyleSheet("background-color: #f8f8f8; border: 1px solid #ccc;")
    stats_layout = QVBoxLayout(stats_widget)
    stats_layout.setContentsMargins(10, 8, 10, 8)

    if total > 0:
        rate = pass_count / total * 100
        stats_text = f"总计: {total} 个测试\n通过: {pass_count}\n失败: {fail_count}\n通过率: {rate:.1f}%"
    else:
        stats_text = "无测试用例"

    stats_label = QLabel(stats_text)
    stats_label.setFont(QFont("Microsoft YaHei", 12, QFont.Bold))
    stats_label.setAlignment(Qt.AlignCenter)
    stats_layout.addWidget(stats_label)

    bottom_splitter.addWidget(stats_widget)

    # 右侧：最新仿真日志
    log_widget = QFrame()
    log_widget.setStyleSheet("border: 1px solid #ccc;")
    log_layout = QVBoxLayout(log_widget)
    log_layout.setContentsMargins(0, 0, 0, 0)

    log_title = QLabel("📄 最新仿真日志")
    log_title.setFont(QFont("Microsoft YaHei", 10, QFont.Bold))
    log_title.setStyleSheet("padding: 5px; background-color: #f0f0f0; border-bottom: 1px solid #ccc;")
    log_layout.addWidget(log_title)

    log_text = QTextEdit()
    log_text.setReadOnly(True)
    log_text.setFont(QFont("Consolas", 9))
    log_text.setStyleSheet("padding: 5px;")
    log_layout.addWidget(log_text)

    bottom_splitter.addWidget(log_widget)

    # 设置底部左右比例 1:3
    bottom_splitter.setStretchFactor(0, 1)
    bottom_splitter.setStretchFactor(1, 3)
    bottom_splitter.setSizes([250, 750])

    main_splitter.addWidget(bottom_splitter)

    # 设置上下比例 2:1
    main_splitter.setStretchFactor(0, 2)
    main_splitter.setStretchFactor(1, 1)
    main_splitter.setSizes([600, 300])

    main_layout.addWidget(main_splitter)

    # 填充列表并设置颜色
    for test_case in test_cases:
        test_name = test_case['name']
        item = QListWidgetItem(test_name)
        result = test_results.get(test_name, 'unknown')
        if result == 'pass':
            item.setForeground(QColor("#2e7d32"))  # 绿色
        elif result == 'fail':
            item.setForeground(QColor("#c62828"))  # 红色
        else:
            item.setForeground(QColor("#9e9e9e"))  # 灰色
        test_list.addItem(item)

    # 加载文件内容
    def load_file_content(text_edit, file_path, encoding='utf-8'):
        try:
            if file_path.exists():
                with open(file_path, 'r', encoding=encoding) as f:
                    content = f.read()
                text_edit.setPlainText(content)
                cursor = text_edit.textCursor()
                cursor.setPosition(0)
                text_edit.setTextCursor(cursor)
            else:
                text_edit.setPlainText(f'文件不存在: {file_path}')
        except Exception as e:
            text_edit.setPlainText(f'读取失败: {e}')

    # 列表选择事件
    def on_test_selected():
        row = test_list.currentRow()
        if row < 0 or row >= len(test_cases):
            return
        test_case = test_cases[row]

        for tab_id, text_edit in tabs.items():
            text_edit.clear()

        load_file_content(tabs['hex'], test_case['hex_file'], 'utf-8')
        load_file_content(tabs['txt'], test_case['txt_file'], 'utf-8')
        load_file_content(tabs['sim_result'], test_case['sim_result'], 'cp936')
        load_file_content(tabs['std_result'], test_case['std_result'], 'utf-8')
        load_file_content(tabs['comparison_result'], test_case['comparison_result'], 'cp936')

    test_list.currentRowChanged.connect(on_test_selected)

    # 加载最新仿真日志到底部右侧
    log_dir = Path("log")
    if log_dir.exists():
        log_files = sorted(log_dir.glob("*.log"), key=os.path.getmtime, reverse=True)
        if log_files:
            latest_log = log_files[0]
            log_title.setText(f"📄 最新仿真日志: {latest_log.name}")
            try:
                with open(latest_log, 'r', encoding='utf-8') as f:
                    log_content = f.read()
                log_text.setPlainText(log_content)
            except Exception as e:
                log_text.setPlainText(f'读取日志失败: {e}')
        else:
            log_text.setPlainText('未找到日志文件')
    else:
        log_text.setPlainText('日志目录不存在')

    # 应用全局样式
    window.setStyleSheet("""
        QMainWindow { background-color: #ffffff; }
        QListWidget { border: 1px solid #ccc; border-radius: 3px; padding: 2px; }
        QListWidget::item { padding: 5px; border-bottom: 1px solid #f0f0f0; }
        QListWidget::item:selected { background-color: #e3f2fd; color: #000; }
        QListWidget::item:hover { background-color: #f5f5f5; }
        QTextEdit { border: 1px solid #ccc; border-radius: 3px; }
    """)

    # 默认选中第一个
    if test_cases:
        test_list.setCurrentRow(0)

    window.show()
    sys.exit(app.exec_())


def clean_generated_files(config_file, tcl_script, exec_script):
    """
    清理生成的文件。
    """
    if os.path.exists(tcl_script):
        os.remove(tcl_script)
        print(f"Removed: {tcl_script}")

    if exec_script and os.path.exists(exec_script):
        os.remove(exec_script)
        print(f"Removed: {exec_script}")

    if config_file and os.path.exists(config_file):
        try:
            with open(config_file, 'r', encoding='utf-8') as f:
                config = json.load(f)
            results_dir = config.get('results_dir')
            if results_dir and os.path.exists(results_dir):
                shutil.rmtree(results_dir)
                print(f"Removed results directory: {results_dir}")
        except Exception as e:
            print(f"Warning: Could not read config file to clean results_dir: {e}")

    temp_file = "_246tb_ex10_result.txt"
    if os.path.exists(temp_file):
        os.remove(temp_file)
        print(f"Removed temporary file: {temp_file}")

def main():
    parser = argparse.ArgumentParser(description="Generate ModelSim batch script from config.")
    parser.add_argument("--config", default="config.json", help="Path to JSON configuration file.")
    parser.add_argument("--exec", action="store_true", help="Generate execution wrapper script to run vsim.")
    parser.add_argument("--output-tcl", default="run_cpu_tests.do", help="Output Tcl script filename (default: run_cpu_tests.do).")
    parser.add_argument("--output-exec", default=None, help="Output execution wrapper filename (default: run_vsim.sh/.bat).")
    parser.add_argument("--clean", action="store_true", help="Clean all generated files (scripts and results directory).")
    parser.add_argument("--not_run", action="store_true", help="NOT !!! Run simulation directly without generating scripts.")
    parser.add_argument("--gui", action="store_true", help="Show test results in GUI after simulation.")
    args = parser.parse_args()

    # 清理模式
    if args.clean:
        if args.output_exec is None:
            default_exec = "run_vsim.bat" if sys.platform.startswith('win') else "run_vsim.sh"
        else:
            default_exec = args.output_exec
        clean_generated_files(args.config, args.output_tcl, default_exec)
        return

    # 正常生成模式
    if not args.config:
        print("Error: --config is required for generation mode.")
        sys.exit(1)

    try:
        with open(args.config, 'r', encoding='utf-8') as f:
            config = json.load(f)
    except Exception as e:
        print(f"Error reading config file: {e}")
        sys.exit(1)

    required_keys = ['ip_files', 'verilog_files', 'testbench_file', 'testdata_dir', 'results_dir', 'imem_file_path', 'imem_readmemh_line']
    for key in required_keys:
        if key not in config:
            print(f"Missing required key in config: {key}")
            sys.exit(1)

    # 处理 verilog_files 和 ip_files：支持文件和目录混合配置
    # 如果配置项是目录，则自动遍历其中所有 Verilog 文件
    print("Collecting Verilog files...")
    config['verilog_files'] = collect_files(config['verilog_files'])
    print(f"  Found {len(config['verilog_files'])} Verilog source files")
    
    if config.get('ip_files'):
        config['ip_files'] = collect_files(config['ip_files'])
        print(f"  Found {len(config['ip_files'])} IP files")
    
    # 输出文件列表（调试信息）
    for f in config['verilog_files']:
        print(f"    - {f}")

    generate_tcl_script(config, args.output_tcl)


    if args.exec:
        if args.output_exec is None:
            default_exec = "run_vsim.bat" if sys.platform.startswith('win') else "run_vsim.sh"
        else:
            default_exec = args.output_exec
        generate_exec_wrapper(args.output_tcl, default_exec)
    elif not args.not_run:
        
        run_vsim(args.output_tcl)
    
    # 如果指定了 --gui 选项，显示 GUI 结果查看器
    if args.gui:
        print("Launching GUI results viewer...")
        show_gui_results(config['results_dir'], config['testdata_dir'])
    
    print("Done.")

if __name__ == '__main__':
    main()