######################################################################
#
# File name : test_simulate.do
# Created on: Wed Apr 01 19:05:48 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.test xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {test_wave.do}

view wave
view structure
view signals

do {test.udo}

run 1000ns
