######################################################################
#
# File name : test_wave.do
# Created on: Wed Apr 01 19:05:48 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
